apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  annotations:
    argocd.argoproj.io/ignore-replicas: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
        - name: ml-service
          image: "{{ .Values.ml.image.repository }}:{{ .Values.ml.image.tag }}"
          ports:
            - containerPort: 7070
          envFrom:
            - secretRef:
                name: team5-secret
          env:
            - name: ROOT_PATH
              value: "/ml"
            - name: KAFKA_USERNAME 
              value: {{ .Values.kafka.users.ml.username | quote }}
            - name: KAFKA_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kafka.credentialsSecretName }} 
                  key: {{ .Values.kafka.users.ml.secretKey }}
            - name: KAFKA_TOPIC_RAW
              value: {{ .Values.kafka.topics.rawReviews.name }}
            - name: KAFKA_TOPIC_PROCESSED
              value: {{ .Values.kafka.topics.processedReviews.name }}
          readinessProbe:
            httpGet:
              path: /ml/consumer/status
              port: 7070
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /ml/health
              port: 7070
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
