replicaCount: 1
ml:
  image:
    repository: ghcr.io/csu-itmo-2025-2/team5-ml
    tag: "sha-f104bc2"
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 256Mi
auth:
  image:
    repository: ghcr.io/csu-itmo-2025-2/team5-auth
    tag: "sha-f104bc2"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 128Mi
producer:
  image:
    repository: ghcr.io/csu-itmo-2025-2/team5-producer
    tag: "sha-f104bc2"
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi
notification:
  image:
    repository: ghcr.io/csu-itmo-2025-2/team5-notification
    tag: "sha-f104bc2"
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 50m
      memory: 200Mi
kafka:
  clusterName: my-cluster
  replicas: 3
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  entityOperator:
    topicOperator:
      bootstrapServers: my-cluster-kafka-bootstrap:9094
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 100m
          memory: 512Mi
    userOperator:
      bootstrapServers: my-cluster-kafka-bootstrap:9094
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 100m
          memory: 512Mi
monitoring:
  enabled: true
  prometheus:
    image:
      repository: quay.io/prometheus/prometheus
      tag: "v2.46.0"
    retention: "12h"
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 50m
        memory: 256Mi
  grafana:
    adminPasswordExternalSecret: true
    externalSecretPath: "kv/data/team5/grafana"
    externalSecretProperty: "ADMIN_PASSWORD"
    ingress:
      enabled: true
      host: grafana-team5.kubepractice.ru
    image:
      repository: grafana/grafana
      tag: "10.3.0"
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 50m
        memory: 100Mi
  loki:
    image:
      repository: grafana/loki
      tag: "2.9.2"
    wal:
      useEmptyDir: true
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    resources:
      requests:
        cpu: "50m"
        memory: "100Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"
  promtail:
    image:
      repository: grafana/promtail
      tag: "2.9.2"
    resources:
      requests:
        cpu: "50m"
        memory: "100Mi"
      limits:
        cpu: "100m"
        memory: "200Mi"
  scrapeTargets:
    - "auth.{{ .Release.Namespace }}.svc.cluster.local:8000"
    - "ml.{{ .Release.Namespace }}.svc.cluster.local:7070"
    - "producer.{{ .Release.Namespace }}.svc.cluster.local:5050"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  ports:
    - name: auth
      port: 8000
    - name: ml
      port: 7070
    - name: producer
      port: 5050
    - name: notification
      port: 7071
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: team5.kubepractice.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - team5.kubepractice.ru
      secretName: team5-prod-secret
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
env: {}
databaseSecretName: "db-credentials"
