replicaCount: 2
ml:
  image:
    repository: ghcr.io/csu-itmo-2025-2/team5-ml
    tag: "sha-b745eb2"
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 50m
      memory: 256Mi
  keda:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    pollingInterval: 30
    cooldownPeriod: 600
    bootstrapServers: "my-cluster-kafka-bootstrap.team5-ns.svc.cluster.local:9092"
    topic: "{{ .Values.kafka.topics.rawReviews.name }}"
    consumerGroup: "{{ .Values.kafka.groups.mlService }}"
    lagThreshold: 10
auth:
  image:
    repository: ghcr.io/csu-itmo-2025-2/team5-auth
    tag: "sha-b745eb2"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 128Mi
producer:
  image:
    repository: ghcr.io/csu-itmo-2025-2/team5-producer
    tag: "sha-b745eb2"
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi
  keda:
    enabled: false
notification:
  image:
    repository: ghcr.io/csu-itmo-2025-2/team5-notification
    tag: "sha-b745eb2"
  resources:
    requests:
      cpu: 150m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  keda:
    enabled: true
    minReplicas: 2
    maxReplicas: 2
    pollingInterval: 30
    cooldownPeriod: 300
    bootstrapServers: "my-cluster-kafka-bootstrap.team5-ns.svc.cluster.local:9092"
    topic: "{{ .Values.kafka.topics.processedReviews.name }}"
    consumerGroup: "{{ .Values.kafka.groups.notificationService }}"
    lagThreshold: 50
ui:
  image:
    repository: ghcr.io/csu-itmo-2025-2/team5-ui
    tag: "sha-b745eb2"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  keda:
    enabled: false
kafka:
  bootstrapServers: "my-cluster-kafka-bootstrap.team5-ns.svc.cluster.local:9092"
  credentialsSecretName: "team5-secret"
  users:
    producer:
      username: "producer-user"
      secretKey: "KAFKA_PRODUCER_PASSWORD"
    ml:
      username: "ml-user"
      secretKey: "KAFKA_ML_PASSWORD"
    notification:
      username: "notification-user"
      secretKey: "KAFKA_NOTIFICATION_PASSWORD"
  topics:
    rawReviews:
      name: "raw-reviews"
      retentionMs: "604800000"
      segmentBytes: "1073741824"
    processedReviews:
      name: "processed-reviews"
      retentionMs: "604800000"
  groups:
    mlService: "ml-service-group"
    notificationService: "notification-group"
monitoring:
  enabled: true
  prometheus:
    image:
      repository: quay.io/prometheus/prometheus
      tag: "v2.46.0"
    retention: "12h"
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 50m
        memory: 256Mi
  grafana:
    adminPasswordExternalSecret: true
    externalSecretPath: "kv/data/team5/grafana"
    externalSecretProperty: "ADMIN_PASSWORD"
    ingress:
      enabled: true
      host: grafana-team5.kubepractice.ru
    image:
      repository: grafana/grafana
      tag: "10.3.0"
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 50m
        memory: 100Mi
  loki:
    image:
      repository: grafana/loki
      tag: "2.9.2"
    wal:
      useEmptyDir: true
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    resources:
      requests:
        cpu: "50m"
        memory: "100Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"
  promtail:
    image:
      repository: grafana/promtail
      tag: "2.9.2"
    resources:
      requests:
        cpu: "50m"
        memory: "100Mi"
      limits:
        cpu: "100m"
        memory: "200Mi"
  scrapeTargets:
    - "auth.team5-ns.svc.cluster.local:8000"
    - "ml.team5-ns.svc.cluster.local:7070"
    - "producer.team5-ns.svc.cluster.local:5050"
    - "my-cluster-kafka-0.team5-ns.svc.cluster.local:9404"
    - "my-cluster-kafka-1.team5-ns.svc.cluster.local:9404"
    - "my-cluster-kafka-2.team5-ns.svc.cluster.local:9404"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  ports:
    - name: auth
      port: 8000
    - name: ml
      port: 7070
    - name: producer
      port: 5050
    - name: notification
      port: 7071
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: team5.kubepractice.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - team5.kubepractice.ru
      secretName: team5-prod-secret
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
env: {}
databaseSecretName: "db-credentials"
