apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: "{{ .Values.notification.image.repository }}:{{ .Values.notification.image.tag }}"
          ports:
            - containerPort: 7071
          envFrom:
            - secretRef:
                name: team5-secret
          env:
            - name: ROOT_PATH
              value: "/notification"
            - name: KAFKA_USERNAME 
              value: {{ .Values.kafka.users.notification.username | quote }}
            - name: KAFKA_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kafka.credentialsSecretName }} 
                  key: {{ .Values.kafka.users.notification.secretKey }}
          readinessProbe:
            httpGet:
              path: /notification/health
              port: 7071
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /notification/health
              port: 7071
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            {{- toYaml .Values.notification.resources | nindent 12 }}

