apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "team5-app.fullname" . }}
  labels:
    {{- include "team5-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "team5-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "team5-app.selectorLabels" . | nindent 8 }}
    spec:
      # {{- with .Values.imagePullSecrets }}
      # imagePullSecrets:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}

      serviceAccountName: {{ include "team5-app.serviceAccountName" . }}

      containers:
        - name: auth-service
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: auth
              containerPort: 8000
          envFrom:
            - secretRef:
                name: {{ .Values.externalSecretName | default "team5-secret" }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /auth/docs
              port: auth
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /auth/docs
              port: auth
            initialDelaySeconds: 10
            periodSeconds: 10

        - name: ml-service
          image: "{{ .Values.ml.image.repository }}:{{ .Values.ml.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: ml
              containerPort: 7070
          envFrom:
            - secretRef:
                name: {{ .Values.externalSecretName | default "team5-secret" }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /ml/docs
              port: ml
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /ml/docs
              port: ml
            initialDelaySeconds: 10
            periodSeconds: 10

        - name: producer-service
          image: "{{ .Values.producer.image.repository }}:{{ .Values.producer.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: producer
              containerPort: 5050
          envFrom:
            - secretRef:
                name: {{ .Values.externalSecretName | default "team5-secret" }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /producer/docs
              port: producer
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /producer/docs
              port: producer
            initialDelaySeconds: 10
            periodSeconds: 10

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
