apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team5-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.hosts.0.host }}
      secretName: {{ .Values.ingress.tls.0.secretName }}

  rules:
    - host: {{ .Values.ingress.hosts.0.host }}
      http:
        paths:
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 8000

          - path: /ml(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: ml-service
                port:
                  number: 7070

          - path: /producer(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: producer-service
                port:
                  number: 5050
