apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "team5-app.fullname" . }}-kafka
  labels:
    {{- include "team5-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "team5-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "team5-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: kafka
    spec:
      securityContext: 
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: kafka
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.kafka.service.port }}
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:{{ .Values.kafka.service.port }}"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://{{ include "team5-app.fullname" . }}-kafka-svc:{{ .Values.kafka.service.port }}"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "{{ include "team5-app.fullname" . }}-zookeeper-svc:{{ .Values.zookeeper.service.port }}"
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}
