apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: producer-service
  template:
    metadata:
      labels:
        app: producer-service
    spec:
      containers:
        - name: producer-service
          image: "{{ .Values.producer.image.repository }}:{{ .Values.producer.image.tag }}"
          ports:
            - containerPort: 5050
          envFrom:
            - secretRef:
                name: team5-secret
          env:                                  
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Release.Name }}-kafka:9092"
          readinessProbe:
            httpGet:
              path: /docs
              port: 5050
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: 5050
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
