apiVersion: v1
kind: Service
metadata:
  name: {{ include "team5-app.fullname" . }}
  labels:
    {{- include "team5-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "team5-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: auth
      port: 8000
      targetPort: auth
      protocol: TCP
    - name: ml
      port: 7070
      targetPort: ml
      protocol: TCP
    - name: producer
      port: 5050
      targetPort: producer
      protocol: TCP
