apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "team5-app.fullname" . }}-zookeeper
  labels:
    {{- include "team5-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "team5-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: zookeeper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "team5-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.zookeeper.service.port }}
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          resources:
            {{- toYaml .Values.zookeeper.resources | nindent 12 }}
